language: node_js
node_js: '7'
before_install:
- npm install -g eslint
- npm install -g babel-cli
script:
- gulp eslint && npm test
deploy:
  provider: npm
  email: jfusco311@gmail.com
  on:
    tags: true
  api_key:
    secure: qVlYorddaKnf9GipkQIxRdsLVYy2cMP/1aFJelCMYdXE0DXtyvBO/5MF/DqHT5n4/wK63Vfy6R32o0rUdYGEZHWeKmyLvrqDwu7U3G2mowW3Ip/bTjZA9D3YIsvdXGgAlD0s4Vlhk2Ra7NueAqj/5oGFlPtuYaxNd5E4UvA7OTV6ykNZlngvA28uFIM0ISdAMxJpxzUbNOlxMf1/t2DYIEshC4t42qy/cIUruk8UJ4y1ZBBr4Qxz+eKWLRU+xSZoNFhzTMsKr8SwmCoZK97BfDFBXQw4ujmJqpxaqKwlui7wth3U9kYiAfQ93WvBKlUDBmRJ5wHNuDe9/paukUN167Zxcq4Jsf0O4of0NLiHpOCZw4MsZiQjGg7w+LxqmHXBPzdHm9BQN9uq0Q8k/WIzKJlRUbwskSDnE8Hoi3T+fvW8Lxow+ooKi/OkVn9zQoQWG/J0TZ20togjGLl5mJg3GVxsyka1vHJNr1j+mSkWfVSW63vRiJuasV4/38F8BX27a9+Qb4ngYT6lvr0i90Uxuxv+6Uos2HWCy/rJ5u6mvLwEIOTyxWizbsXm+5Qy0+3+TsiZAnTgtajgHHSxvWLmk3CT5m2h8WK2xwBPgNcU3bH4VdjIBcxgkqBaDBjjzzzPIjXeZVwilAHaroXzAECkGkVsXocebhsLqwYKZ1o9BM8=
